import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, ExternalLink } from "lucide-react";

import { FIELD_PROBLEMS, getProblem, getResource, getSkill } from "@/lib/commerce-fieldbook";

export function generateStaticParams() { return FIELD_PROBLEMS.map(({ slug }) => ({ slug })); }

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params; const problem = getProblem(slug); if (!problem) return {};
  return { title: { absolute: `${problem.title} | Beseam Commerce Fieldbook` }, description: problem.summary, alternates: { canonical: `/resources/problems/${slug}` } };
}

function ListBlock({ title, items }: { title: string; items: string[] }) { return <section className="border-t border-black/22 pt-6"><h2 className="font-serif text-[30px] tracking-[-0.03em]">{title}</h2><ul className="mt-5 border-t border-black/16">{items.map((item) => <li key={item} className="flex gap-3 border-b border-black/16 py-4 text-[15px] leading-relaxed text-black/64"><span className="mt-2 h-1.5 w-1.5 shrink-0 bg-[var(--beseam-accent)]" />{item}</li>)}</ul></section>; }

export default async function ProblemPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const problem = getProblem(slug); if (!problem) notFound();
  const skills = problem.skillSlugs.map(getSkill).filter(Boolean); const projects = problem.projectSlugs.map(getResource).filter(Boolean);
  return <div className="bg-[var(--beseam-surface)] text-[var(--beseam-ink)]"><section className="border-b border-black/18"><div className="mx-auto max-w-[92rem] px-5 py-20 sm:px-8 lg:px-10"><Link href="/resources/problems" className="font-mono text-[10px] uppercase tracking-[0.1em] text-[var(--beseam-accent)]">Fieldbook / {problem.category}</Link><div className="mt-7 grid gap-10 lg:grid-cols-[minmax(0,0.82fr)_minmax(0,1.18fr)] lg:items-end lg:gap-20"><h1 className="max-w-[12ch] font-serif text-[clamp(3.2rem,5.2vw,5.4rem)] leading-[0.98] tracking-[-0.05em]">{problem.title}</h1><p className="max-w-2xl text-[19px] leading-relaxed text-black/64">{problem.summary}</p></div></div></section><div className="mx-auto grid max-w-[92rem] gap-12 px-5 py-16 sm:px-8 lg:grid-cols-[minmax(0,0.72fr)_minmax(0,1.28fr)] lg:gap-20 lg:px-10"><div className="space-y-12"><ListBlock title="Signals" items={problem.signals} /><ListBlock title="Evidence to collect" items={problem.evidence} /></div><div className="space-y-12"><ListBlock title="First investigation moves" items={problem.firstMoves} />{skills.length > 0 && <section className="border-t border-black/22 pt-6"><h2 className="font-serif text-[30px] tracking-[-0.03em]">Related agent skills</h2><div className="mt-5 border-t border-black/16">{skills.map((skill) => skill && <Link key={skill.slug} href={`/resources/skills/${skill.slug}`} className="group flex items-center justify-between gap-5 border-b border-black/16 py-5"><div><h3 className="text-[16px] font-semibold">{skill.title}</h3><p className="mt-2 text-[13px] leading-relaxed text-black/54">{skill.summary}</p></div><ArrowRight className="h-4 w-4 shrink-0 text-[var(--beseam-accent)] transition-transform group-hover:translate-x-0.5" /></Link>)}</div></section>}{projects.length > 0 && <section className="border-t border-black/22 pt-6"><h2 className="font-serif text-[30px] tracking-[-0.03em]">Supporting projects and references</h2><div className="mt-5 grid gap-px border border-black/16 bg-black/16 sm:grid-cols-2">{projects.map((project) => project && <a key={project.slug} href={project.url} target={project.url.startsWith("http") ? "_blank" : undefined} rel={project.url.startsWith("http") ? "noreferrer" : undefined} className="bg-[var(--beseam-surface)] p-5 hover:bg-[var(--beseam-panel)]"><p className="font-mono text-[9px] uppercase tracking-[0.09em] text-black/42">{project.kind} · {project.maturity}</p><h3 className="mt-3 flex items-center gap-2 text-[16px] font-semibold">{project.name}{project.url.startsWith("http") && <ExternalLink className="h-3.5 w-3.5 text-[var(--beseam-accent)]" />}</h3><p className="mt-3 text-[13px] leading-relaxed text-black/55">{project.summary}</p><p className="mt-4 font-mono text-[8px] uppercase tracking-[0.08em] text-black/34">Reviewed {project.reviewedAt}</p></a>)}</div></section>}</div></div></div>;
}
