import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";

import { FIELD_SKILLS } from "@/lib/commerce-fieldbook";

export const metadata: Metadata = { title: { absolute: "Agent Skills | Beseam Commerce Fieldbook" }, description: "Reusable ecommerce workflows for Claude, coding agents, other assistants, and human operators.", alternates: { canonical: "/resources/skills" } };

export default function SkillsIndexPage() { return <div className="bg-[var(--beseam-technical)] text-white"><section className="border-b border-white/18"><div className="mx-auto max-w-[92rem] px-5 py-20 sm:px-8 lg:px-10"><Link href="/resources" className="font-mono text-[10px] uppercase tracking-[0.1em] text-[var(--beseam-accent-soft)]">Commerce Fieldbook / Agent skills</Link><h1 className="mt-7 max-w-[11ch] font-serif text-[clamp(3.2rem,5.2vw,5.4rem)] leading-[0.98] tracking-[-0.05em]">Reusable workflows, not magic prompts.</h1><p className="mt-7 max-w-2xl text-[18px] leading-relaxed text-white/62">Each skill states its inputs, expected outputs, checks, supporting projects, and the conclusions it is not allowed to make.</p></div></section><section><div className="mx-auto grid max-w-[92rem] gap-px bg-white/18 sm:grid-cols-2 lg:grid-cols-3">{FIELD_SKILLS.map((skill) => <Link key={skill.slug} href={`/resources/skills/${skill.slug}`} className="group bg-[var(--beseam-technical)] p-7 hover:bg-[var(--beseam-technical-hover)]"><p className="font-mono text-[9px] uppercase tracking-[0.1em] text-[var(--beseam-accent-soft)]">{skill.category}</p><h2 className="mt-6 text-[21px] font-semibold leading-snug">{skill.title}</h2><p className="mt-4 text-[14px] leading-relaxed text-white/55">{skill.summary}</p><p className="mt-6 font-mono text-[9px] uppercase tracking-[0.09em] text-white/34">Works with {skill.worksWith.join(" · ")}</p><span className="mt-7 inline-flex items-center gap-2 text-[12px] font-semibold text-[var(--beseam-accent-soft)]">Open skill <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5" /></span></Link>)}</div></section></div>; }
