import type { Metadata } from "next";
import PlatformAuditPage from "@/components/beseam/platform-audit-page";
import type { Finding } from "@/components/beseam/sample-findings";

export const metadata: Metadata = {
  title: "Adobe Commerce (Magento) product data audit",
  description:
    "Check which product attributes reach your Magento JSON-LD. Get an evidence-backed list of schema gaps and a proposed template fix for your theme.",
  keywords: [
    "Adobe Commerce structured data",
    "Magento product schema",
    "Magento configurable product pricing",
    "Magento JSON-LD template",
    "Magento multi-store canonical",
  ],
};

const findings: Finding[] = [
  {
    title: "Default schema emits a bare product",
    severity: "critical",
    description:
      "Magento's core structured data output covers name, image, and price. Material, certification, size guide, compatibility, and every other attribute in the set stay in the database. A parser reading the page sees a product it can identify and nothing it can evaluate.",
    fix: `// app/code/YourModule/view/frontend/templates/product/jsonld.phtml
<?php
$product = $block->getProduct();
$schema = [
    '@context' => 'https://schema.org',
    '@type' => 'Product',
    'name' => $product->getName(),
    'description' => strip_tags($product->getDescription()),
    'brand' => ['@type' => 'Brand', 'name' => $product->getAttributeText('brand')],
    'material' => $product->getAttributeText('material'),
    'additionalProperty' => [],
];
// Add all visible attributes as PropertyValue
foreach ($product->getAttributes() as $attr) {
    if ($attr->getIsVisibleOnFront() && $product->getData($attr->getAttributeCode())) {
        $schema['additionalProperty'][] = [
            '@type' => 'PropertyValue',
            'name' => $attr->getFrontendLabel(),
            'value' => $product->getAttributeText($attr->getAttributeCode())
                       ?: $product->getData($attr->getAttributeCode()),
        ];
    }
}
?>
<script type="application/ld+json">
<?= json_encode($schema, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT) ?>
</script>`,
  },
  {
    title: "Configurable products quote a price range",
    severity: "critical",
    description:
      'A configurable product renders "From $49.00" in both the UI and the schema. The Offer describes the parent, not the simple product the shopper selected. An assistant asked what a specific size costs can only repeat the starting price, which is not what was asked.',
    fix: `// Generate per-variant Offer schema for configurable products
$offers = [];
foreach ($product->getTypeInstance()->getUsedProducts($product) as $child) {
    $offers[] = [
        '@type' => 'Offer',
        'name' => $child->getName(),
        'sku' => $child->getSku(),
        'price' => $child->getFinalPrice(),
        'priceCurrency' => $store->getCurrentCurrencyCode(),
        'availability' => $child->isSaleable()
            ? 'https://schema.org/InStock'
            : 'https://schema.org/OutOfStock',
        'url' => $product->getProductUrl(),
    ];
}
$schema['offers'] = $offers;`,
  },
  {
    title: "Store views conflict on canonical and currency",
    severity: "high",
    description:
      "One product served across store views produces multiple URLs with different currencies and translations. Without correct canonical and hreflang tags, a crawler indexes the duplicates and may retain the view whose price and language belong to a different market than the shopper.",
    fix: `<!-- In catalog_product_view.xml layout, add canonical and hreflang -->
<head>
  <link rel="canonical" href="<?= $block->getProduct()->getProductUrl() ?>" />
  <!-- For each store view: -->
  <link rel="alternate" hreflang="en-us"
        href="https://us.yourstore.com/product-url" />
  <link rel="alternate" hreflang="en-gb"
        href="https://uk.yourstore.com/product-url" />
</head>

<!-- Ensure schema uses the canonical store view's currency -->
"priceCurrency": "<?= $block->getCurrentCurrencyCode() ?>"`,
  },
  {
    title: "Layered navigation pages lack list schema",
    severity: "medium",
    description:
      "Filtered category URLs generated by layered navigation render product grids with no CollectionPage or ItemList schema. The filter that defines the set lives in the URL and not in the data, so nothing readable states what the page is a list of.",
    fix: `// Add ItemList schema to category pages
// app/code/YourModule/view/frontend/templates/category/jsonld.phtml
<?php
$category = $block->getCurrentCategory();
$products = $block->getProductCollection();
$items = [];
foreach ($products as $i => $product) {
    $items[] = [
        '@type' => 'ListItem',
        'position' => $i + 1,
        'url' => $product->getProductUrl(),
    ];
}
$schema = [
    '@context' => 'https://schema.org',
    '@type' => 'CollectionPage',
    'name' => $category->getName(),
    'description' => strip_tags($category->getDescription()),
    'mainEntity' => [
        '@type' => 'ItemList',
        'numberOfItems' => count($items),
        'itemListElement' => $items,
    ],
];
?>
<script type="application/ld+json">
<?= json_encode($schema, JSON_UNESCAPED_SLASHES) ?>
</script>`,
  },
];

const contextParagraphs = [
  "Adobe Commerce holds more product data than most platforms — EAV attributes, attribute sets, per-store-view values. Very little of it reaches structured data. The core output covers name, image, and a basic Offer, and stops there regardless of how many attributes the set defines.",
  "Configurable products carry the second gap. The schema follows the UI and states a price range rather than an Offer per simple child. A shopper asking about one size or color gets a starting price back, which is not the number needed to decide.",
  "Store views compound both. The same product served on several views with different currencies, translations, and URLs will be crawled several times. Without correct canonical and hreflang, the version a crawler settles on may carry the price and language of a market the shopper is not in.",
  "Beseam fetches your storefront the way a crawler does, parses the rendered JSON-LD, and reports which attributes are present in the catalog and absent from the page. It proposes the template or block change for your version. Beseam does not deploy code to your store.",
];

const otherPlatforms = [
  { name: "Shopify", href: "/audit/shopify" },
  { name: "WooCommerce", href: "/audit/woocommerce" },
  { name: "BigCommerce", href: "/audit/bigcommerce" },
  {
    name: "Salesforce Commerce Cloud",
    href: "/audit/salesforce-commerce-cloud",
  },
  { name: "Headless / Custom", href: "/audit/custom" },
];

export default function MagentoAuditPage() {
  return (
    <PlatformAuditPage
      platform="Adobe Commerce (Magento)"
      headline="Your product attributes stop before the JSON-LD"
      description="Beseam reads the structured data your Magento templates render on product, configurable, and category pages, then compares it with the attributes your catalog holds. The output is an evidence-backed list of gaps and a proposed template fix."
      contextParagraphs={contextParagraphs}
      findings={findings}
      otherPlatforms={otherPlatforms}
    />
  );
}
